# Generated by Django 3.1.7 on 2021-02-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
