# Generated by Django 3.1.7 on 2021-02-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20210223_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='hight',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='width',
            field=models.TextField(blank=True),
        ),
    ]
